# Generated by Django 4.2.2 on 2023-07-03 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("mu", models.FloatField(default=25.0)),
                ("sigma", models.FloatField(default=8.33333)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "docker_image",
                    models.CharField(blank=True, default="", max_length=2000),
                ),
            ],
        ),
    ]
