# Generated by Django 4.2.2 on 2023-07-05 16:52

import django.db.models.deletion
from django.db import migrations, models

import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0002_bot"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True
                    ),
                ),
                (
                    "updated_at",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True
                    ),
                ),
                ("uuid", models.UUIDField()),
                ("run_id", models.BigIntegerField()),
                ("date", models.DateTimeField(null=True)),
                ("seed", models.PositiveBigIntegerField(null=True)),
                ("width", models.IntegerField(null=True)),
                ("height", models.IntegerField(null=True)),
                ("replay", models.FileField(default=None, upload_to="")),
            ],
            options={
                "verbose_name_plural": "matches",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="is_npc",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bot",
            name="sigma",
            field=models.FloatField(default=8.333333333333334),
        ),
        migrations.CreateModel(
            name="MatchResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("docker_image", models.CharField(max_length=2000)),
                ("rank", models.IntegerField()),
                ("mu", models.FloatField()),
                ("sigma", models.FloatField()),
                ("last_frame_alive", models.IntegerField()),
                ("error_log", models.FileField(default=None, upload_to="")),
                (
                    "created_at",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True
                    ),
                ),
                (
                    "updated_at",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True
                    ),
                ),
                (
                    "bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="tournament.bot",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="tournament.match",
                    ),
                ),
            ],
        ),
    ]
