# Generated by Django 4.2.2 on 2023-07-05 16:57

import django.utils.timezone
from django.db import migrations

import django_extensions.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0003_match_user_is_npc_alter_bot_sigma_matchresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="created_at",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bot",
            name="updated_at",
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True),
        ),
    ]
