# Generated by Django 4.2.2 on 2023-07-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0004_bot_created_at_bot_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_npc",
            field=models.BooleanField(default=False, verbose_name="npc"),
        ),
    ]
