# Generated by Django 4.2.2 on 2023-07-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tournament", "0005_alter_user_is_npc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_npc",
            field=models.BooleanField(default=False, verbose_name="NPC"),
        ),
    ]
